/**
 * Generated by `npx supabase gen types typescript --project-id <id>`.
 *
 * Until you run the generator, this file uses a hand-authored shape
 * that matches the migrations. Regenerate it with:
 *
 *   npx supabase gen types typescript --project-id <projectId> > src/types/database.ts
 *
 * The shape below is what the generator would emit for the schema in
 * /supabase/migrations. Keep in sync if migrations change.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = "admin" | "member";
export type MemberStatus = "pending" | "active" | "suspended";
export type MeetingStatus =
  | "draft"
  | "agenda_published"
  | "live"
  | "ended"
  | "minutes_published"
  | "cancelled";
export type ItemStatus =
  | "pending"
  | "in_progress"
  | "resolved"
  | "deferred"
  | "tabled";
export type MotionStatus =
  | "raised"
  | "seconded"
  | "voting_open"
  | "passed"
  | "rejected"
  | "withdrawn";
export type VoteChoice = "yes" | "no" | "abstain";
export type NotificationKind =
  | "agenda_published"
  | "meeting_starting"
  | "vote_opened"
  | "minutes_published"
  | "motion_seconded"
  | "item_resolved"
  | "approval_granted"
  | "approval_pending";

export interface ProfileRow {
  id: string;
  email: string;
  full_name: string;
  role: UserRole;
  status: MemberStatus;
  title: string | null;
  avatar_url: string | null;
  approved_by: string | null;
  approved_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface MeetingRow {
  id: string;
  title: string;
  description: string | null;
  location: string | null;
  scheduled_at: string;
  duration_min: number;
  status: MeetingStatus;
  created_by: string;
  agenda_published_at: string | null;
  started_at: string | null;
  ended_at: string | null;
  minutes_published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface AgendaItemRow {
  id: string;
  meeting_id: string;
  title: string;
  description: string | null;
  allocated_min: number;
  order_index: number;
  status: ItemStatus;
  outcome_notes: string | null;
  carried_from_id: string | null;
  started_at: string | null;
  ended_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface AttendanceRow {
  meeting_id: string;
  user_id: string;
  checked_in_at: string;
}

export interface MotionRow {
  id: string;
  meeting_id: string;
  agenda_item_id: string;
  raised_by: string;
  seconded_by: string | null;
  text: string;
  status: MotionStatus;
  opened_at: string | null;
  closed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface VoteRow {
  motion_id: string;
  user_id: string;
  choice: VoteChoice;
  voted_at: string;
}

export interface MinutesRow {
  meeting_id: string;
  body: string;
  generated_at: string;
  published_at: string | null;
  published_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface MinutesAckRow {
  meeting_id: string;
  user_id: string;
  acknowledged_at: string;
}

export interface NotificationRow {
  id: string;
  user_id: string;
  kind: NotificationKind;
  title: string;
  body: string | null;
  meeting_id: string | null;
  read_at: string | null;
  created_at: string;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyInsert = Record<string, any>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyUpdate = Record<string, any>;

export interface Database {
  public: {
    Tables: {
      profiles: { Row: ProfileRow; Insert: AnyInsert; Update: AnyUpdate };
      meetings: { Row: MeetingRow; Insert: AnyInsert; Update: AnyUpdate };
      agenda_items: { Row: AgendaItemRow; Insert: AnyInsert; Update: AnyUpdate };
      attendance: { Row: AttendanceRow; Insert: AnyInsert; Update: AnyUpdate };
      motions: { Row: MotionRow; Insert: AnyInsert; Update: AnyUpdate };
      votes: { Row: VoteRow; Insert: AnyInsert; Update: AnyUpdate };
      minutes: { Row: MinutesRow; Insert: AnyInsert; Update: AnyUpdate };
      minutes_acknowledgments: { Row: MinutesAckRow; Insert: AnyInsert; Update: AnyUpdate };
      notifications: { Row: NotificationRow; Insert: AnyInsert; Update: AnyUpdate };
    };
    Views: {
      meeting_quorum: { Row: { meeting_id: string; denominator: number; present: number; quorum_met: boolean } };
    };
    Enums: {
      user_role: UserRole;
      member_status: MemberStatus;
      meeting_status: MeetingStatus;
      item_status: ItemStatus;
      motion_status: MotionStatus;
      vote_choice: VoteChoice;
      notification_kind: NotificationKind;
    };
  };
}